---
title: "Developing Data Products Week2 Project"
author: "Raghu"
date: "January 15, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Here are the Major cities in Masachusetts. The circles are sized by population in the cities with population popup, sourced from [Here](https://www.citypopulation.de/USA-Massachusetts.html)

``` {r,echo=TRUE,messages=FALSE}
suppressPackageStartupMessages(library(ggmap))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(leaflet))
cities <-  c("Boston MA", "Worcester MA","Springfield MA","Lowell MA",
                "Brockton MA","Cambridge MA","New Bedford MA", "Quincy MA","Lynn MA")
lonlat <- suppressMessages(geocode(cities))

md_cities <- data.frame(name = c("Boston MA", "Worcester MA","Springfield MA","Lowell MA",
                                 "Brockton MA","Cambridge MA","New Bedford MA", "Quincy MA","Lynn MA"),
                        pop = c(667137,184815,154341,110699,95314,110402,94958,93618,92457),
                        lat = lonlat$lat,
                        lng = lonlat$lon)

suppressMessages(md_cities %>%
        leaflet() %>%
        addTiles() %>%
        addCircles(weight = 1, radius = sqrt(md_cities$pop) * 20) %>%
        addMarkers(clusterOptions = markerClusterOptions(), popup = paste(md_cities$pop, " [2015]")))
```